name: Update and Factory Rebuild

on:
  schedule:
    - cron: "5 21 * * *"  # Esegui alle 21:05 ogni giorno
  workflow_dispatch:        # Permette di avviare manualmente il workflow

jobs:
  update_and_rebuild:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Git
      - name: Set up Git
        run: |
          git config --global user.name "tuo_nome"
          git config --global user.email "tuo_email@example.com"

      # Esegui lo script di aggiornamento
      - name: Run update script
        run: bash ./update_and_deploy.sh

      # Avvia il deploy su Render utilizzando le variabili segrete
      - name: Trigger Render Deploy for eighth URL
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_URL }}
